[package]
name = "autorest_standalone"
version = "0.1.0"
authors = ["jeremyletang <letang.jeremy@gmail.com>"]

[dependencies]
autorest = { path = "../autorest" }
hyper = "0.9.12"
serde = "0.8.18"
serde_json = "0.8.3"
serde_derive = "0.8.18"
