FROM debian:latest
MAINTAINER Jeremy Letang <letang.jeremy@gmail.com>

RUN apt-get update && \
    apt-get install -y curl build-essential libssl-dev

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2017-01-19

RUN mkdir /srcs
WORKDIR /srcs

CMD ["/root/.cargo/bin/cargo", "build", "--manifest-path=./arrakis_standalone/Cargo.toml", "--release", "-j8"]