[package]
name = "arrakis_iron"
version = "0.1.0"
authors = ["jeremyletang <letang.jeremy@gmail.com>"]

[dependencies]
arrakis = { path = "../arrakis" }
iron = "0.4.0"
urlencoded = "0.4.1"
serde = "0.8.18"
serde_json = "0.8.3"
